--------------------------------------------------------
--  파일이 생성됨 - 수요일-5월-13-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTICLE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ARTICLE" 
   (	"ID" NUMBER, 
	"WRITERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index ARTICLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ARTICLE_PK" ON "SCOTT"."ARTICLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ARTICLE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ARTICLE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ARTICLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ARTICLE" MODIFY ("WRITERNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ARTICLE" ADD CONSTRAINT "ARTICLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  
  
  
  
  
  INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('246', 'aa', '12343', 'sdsd', 'ssdsd');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('248', '임동민', '1234', '내가쓴다', '야');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE) VALUES ('247', '임동민', '1234', '내가쓴다1');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('1', '초기값', '134234', '임동민', '나짱짱');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('5', '임동민2', '124', '내가쓴다2', '읽어봐2');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('6', '임동민3', '125', '내가쓴다3', '읽어봐3');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('7', '임동민4', '126', '내가쓴다4', '읽어봐4');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('8', '임동민5', '127', '내가쓴다5', '읽어봐5');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('9', '임동민6', '128', '내가쓴다6', '읽어봐6');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('10', '임동민7', '129', '내가쓴다7', '읽어봐7');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('11', '임동민8', '130', '내가쓴다8', '읽어봐8');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('12', '임동민9', '131', '내가쓴다9', '읽어봐9');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('13', '임동민10', '132', '내가쓴다10', '읽어봐10');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('14', '임동민11', '133', '내가쓴다11', '읽어봐11');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('15', '임동민12', '134', '내가쓴다12', '읽어봐12');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('16', '임동민13', '135', '내가쓴다13', '읽어봐13');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('17', '임동민14', '136', '내가쓴다14', '읽어봐14');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('18', '임동민15', '137', '내가쓴다15', '읽어봐15');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('19', '임동민16', '138', '내가쓴다16', '읽어봐16');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('20', '임동민17', '139', '내가쓴다17', '읽어봐17');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('21', '임동민18', '140', '내가쓴다18', '읽어봐18');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('22', '임동민19', '141', '내가쓴다19', '읽어봐19');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('23', '임동민20', '142', '내가쓴다20', '읽어봐20');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('24', '임동민21', '143', '내가쓴다21', '읽어봐21');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('25', '임동민22', '144', '내가쓴다22', '읽어봐22');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('26', '임동민23', '145', '내가쓴다23', '읽어봐23');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('27', '임동민24', '146', '내가쓴다24', '읽어봐24');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('28', '임동민25', '147', '내가쓴다25', '읽어봐25');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('29', '임동민26', '148', '내가쓴다26', '읽어봐26');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('30', '임동민27', '149', '내가쓴다27', '읽어봐27');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('31', '임동민28', '150', '내가쓴다28', '읽어봐28');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('32', '임동민29', '151', '내가쓴다29', '읽어봐29');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('33', '임동민30', '152', '내가쓴다30', '읽어봐30');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('34', '임동민31', '153', '내가쓴다31', '읽어봐31');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('35', '임동민32', '154', '내가쓴다32', '읽어봐32');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('36', '임동민33', '155', '내가쓴다33', '읽어봐33');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('37', '임동민34', '156', '내가쓴다34', '읽어봐34');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('38', '임동민35', '157', '내가쓴다35', '읽어봐35');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('39', '임동민36', '158', '내가쓴다36', '읽어봐36');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('40', '임동민37', '159', '내가쓴다37', '읽어봐37');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('41', '임동민38', '160', '내가쓴다38', '읽어봐38');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('42', '임동민39', '161', '내가쓴다39', '읽어봐39');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('43', '임동민40', '162', '내가쓴다40', '읽어봐40');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('44', '임동민41', '163', '내가쓴다41', '읽어봐41');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('45', '임동민42', '164', '내가쓴다42', '읽어봐42');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('46', '임동민43', '165', '내가쓴다43', '읽어봐43');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('47', '임동민44', '166', '내가쓴다44', '읽어봐44');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('48', '임동민45', '167', '내가쓴다45', '읽어봐45');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('49', '임동민46', '168', '내가쓴다46', '읽어봐46');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('50', '임동민47', '169', '내가쓴다47', '읽어봐47');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('51', '임동민48', '170', '내가쓴다48', '읽어봐48');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('52', '임동민49', '171', '내가쓴다49', '읽어봐49');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('53', '임동민50', '172', '내가쓴다50', '읽어봐50');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('54', '임동민51', '173', '내가쓴다51', '읽어봐51');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('55', '임동민52', '174', '내가쓴다52', '읽어봐52');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('56', '임동민53', '175', '내가쓴다53', '읽어봐53');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('57', '임동민54', '176', '내가쓴다54', '읽어봐54');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('58', '임동민55', '177', '내가쓴다55', '읽어봐55');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('59', '임동민56', '178', '내가쓴다56', '읽어봐56');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('60', '임동민57', '179', '내가쓴다57', '읽어봐57');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('61', '임동민58', '180', '내가쓴다58', '읽어봐58');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('62', '임동민59', '181', '내가쓴다59', '읽어봐59');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('63', '임동민60', '182', '내가쓴다60', '읽어봐60');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('64', '임동민61', '183', '내가쓴다61', '읽어봐61');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('65', '임동민62', '184', '내가쓴다62', '읽어봐62');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('66', '임동민63', '185', '내가쓴다63', '읽어봐63');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('67', '임동민64', '186', '내가쓴다64', '읽어봐64');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('68', '임동민65', '187', '내가쓴다65', '읽어봐65');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('69', '임동민66', '188', '내가쓴다66', '읽어봐66');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('70', '임동민67', '189', '내가쓴다67', '읽어봐67');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('71', '임동민68', '190', '내가쓴다68', '읽어봐68');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('72', '임동민69', '191', '내가쓴다69', '읽어봐69');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('73', '임동민70', '192', '내가쓴다70', '읽어봐70');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('74', '임동민71', '193', '내가쓴다71', '읽어봐71');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('75', '임동민72', '194', '내가쓴다72', '읽어봐72');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('76', '임동민73', '195', '내가쓴다73', '읽어봐73');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('77', '임동민74', '196', '내가쓴다74', '읽어봐74');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('78', '임동민75', '197', '내가쓴다75', '읽어봐75');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('79', '임동민76', '198', '내가쓴다76', '읽어봐76');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('80', '임동민77', '199', '내가쓴다77', '읽어봐77');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('81', '임동민78', '200', '내가쓴다78', '읽어봐78');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('82', '임동민79', '201', '내가쓴다79', '읽어봐79');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('83', '임동민80', '202', '내가쓴다80', '읽어봐80');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('84', '임동민81', '203', '내가쓴다81', '읽어봐81');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('85', '임동민82', '204', '내가쓴다82', '읽어봐82');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('86', '임동민83', '205', '내가쓴다83', '읽어봐83');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('87', '임동민84', '206', '내가쓴다84', '읽어봐84');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('88', '임동민85', '207', '내가쓴다85', '읽어봐85');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('89', '임동민86', '208', '내가쓴다86', '읽어봐86');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('90', '임동민87', '209', '내가쓴다87', '읽어봐87');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('91', '임동민88', '210', '내가쓴다88', '읽어봐88');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('92', '임동민89', '211', '내가쓴다89', '읽어봐89');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('93', '임동민90', '212', '내가쓴다90', '읽어봐90');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('94', '임동민91', '213', '내가쓴다91', '읽어봐91');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('95', '임동민92', '214', '내가쓴다92', '읽어봐92');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('96', '임동민93', '215', '내가쓴다93', '읽어봐93');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('97', '임동민94', '216', '내가쓴다94', '읽어봐94');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('98', '임동민95', '217', '내가쓴다95', '읽어봐95');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('99', '임동민96', '218', '내가쓴다96', '읽어봐96');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('100', '임동민97', '219', '내가쓴다97', '읽어봐97');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('101', '임동민98', '220', '내가쓴다98', '읽어봐98');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('102', '임동민99', '221', '내가쓴다99', '읽어봐99');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('103', '임동민100', '222', '내가쓴다100', '읽어봐100');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('104', '임동민101', '223', '내가쓴다101', '읽어봐101');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('105', '임동민102', '224', '내가쓴다102', '읽어봐102');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('106', '임동민103', '225', '내가쓴다103', '읽어봐103');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('107', '임동민104', '226', '내가쓴다104', '읽어봐104');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('108', '임동민105', '227', '내가쓴다105', '읽어봐105');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('109', '임동민106', '228', '내가쓴다106', '읽어봐106');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('110', '임동민107', '229', '내가쓴다107', '읽어봐107');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('111', '임동민108', '230', '내가쓴다108', '읽어봐108');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('112', '임동민109', '231', '내가쓴다109', '읽어봐109');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('113', '임동민110', '232', '내가쓴다110', '읽어봐110');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('114', '임동민111', '233', '내가쓴다111', '읽어봐111');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('115', '임동민112', '234', '내가쓴다112', '읽어봐112');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('116', '임동민113', '235', '내가쓴다113', '읽어봐113');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('117', '임동민114', '236', '내가쓴다114', '읽어봐114');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('118', '임동민115', '237', '내가쓴다115', '읽어봐115');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('119', '임동민116', '238', '내가쓴다116', '읽어봐116');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('120', '임동민117', '239', '내가쓴다117', '읽어봐117');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('121', '임동민118', '240', '내가쓴다118', '읽어봐118');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('122', '임동민119', '241', '내가쓴다119', '읽어봐119');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('123', '임동민120', '242', '내가쓴다120', '읽어봐120');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('124', '임동민121', '243', '내가쓴다121', '읽어봐121');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('125', '임동민122', '244', '내가쓴다122', '읽어봐122');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('126', '임동민123', '245', '내가쓴다123', '읽어봐123');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('127', '임동민124', '246', '내가쓴다124', '읽어봐124');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('128', '임동민125', '247', '내가쓴다125', '읽어봐125');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('129', '임동민126', '248', '내가쓴다126', '읽어봐126');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('130', '임동민127', '249', '내가쓴다127', '읽어봐127');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('131', '임동민128', '250', '내가쓴다128', '읽어봐128');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('132', '임동민129', '251', '내가쓴다129', '읽어봐129');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('133', '임동민130', '252', '내가쓴다130', '읽어봐130');
INSERT INTO "SCOTT"."ARTICLE" (ID, WRITERNAME, PASSWORD, TITLE, CONTENT) VALUES ('134', '임동민131', '253', '내가쓴다131', '읽어봐131');

  
  
  
  
  
  
  
