--------------------------------------------------------
--  파일이 생성됨 - 일요일-5월-17-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HEARTLINKRECORD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."HEARTLINKRECORD" 
   (	"ANSWER1" VARCHAR2(20 BYTE), 
	"ANSWER2" VARCHAR2(20 BYTE), 
	"ANSWER3" VARCHAR2(20 BYTE), 
	"ANSWER4" VARCHAR2(20 BYTE), 
	"ANSWER5" VARCHAR2(20 BYTE), 
	"ANSWER6" VARCHAR2(20 BYTE), 
	"ANSWER7" VARCHAR2(20 BYTE), 
	"ANSWER8" VARCHAR2(20 BYTE), 
	"ANSWER9" VARCHAR2(20 BYTE), 
	"ANSWER10" VARCHAR2(20 BYTE), 
	"ANSWER11" VARCHAR2(20 BYTE), 
	"ANSWER12" VARCHAR2(20 BYTE), 
	"ANSWER13" VARCHAR2(20 BYTE), 
	"ANSWER14" VARCHAR2(20 BYTE), 
	"ANSWER15" VARCHAR2(20 BYTE), 
	"ANSWER16" VARCHAR2(20 BYTE), 
	"ANSWER17" VARCHAR2(20 BYTE), 
	"ANSWER18" VARCHAR2(20 BYTE), 
	"ANSWER19" VARCHAR2(20 BYTE), 
	"ANSWER20" VARCHAR2(20 BYTE), 
	"ANSWER21" VARCHAR2(20 BYTE), 
	"ANSWER22" VARCHAR2(20 BYTE), 
	"ANSWER23" VARCHAR2(20 BYTE), 
	"ANSWER24" VARCHAR2(20 BYTE), 
	"RECORDID" VARCHAR2(20 BYTE), 
	"NUM" NUMBER(20,0), 
	"QUESTIONNUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HEARTLINKRECORD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."HEARTLINKRECORD" MODIFY ("RECORDID" NOT NULL ENABLE);
  
  
  
  
  
  
INSERT INTO "SCOTT"."HEARTLINKRECORD" (ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, ANSWER8, ANSWER9, ANSWER10, ANSWER11, ANSWER12, ANSWER13, ANSWER14, ANSWER15, ANSWER16, ANSWER17, ANSWER18, ANSWER19, ANSWER20, ANSWER21, ANSWER22, ANSWER23, ANSWER24, RECORDID, NUM, QUESTIONNUM) VALUES ('양념', '사랑', '짜장 ', '축구', '콜라', '강아지', '단팥빵', '향수냄새', '하얀피부', '비빔냉면', '많게 본다', '줍는다', '있다', '세글자', '자이로드롭', '영화관', '괜찮다', '얼굴', '단색', '낮져밤이', '먹고간다', '국내', '도망간다', '그렇다', 'webapp', '20', 'a1_b1');
INSERT INTO "SCOTT"."HEARTLINKRECORD" (ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, ANSWER8, ANSWER9, ANSWER10, ANSWER11, ANSWER12, ANSWER13, ANSWER14, ANSWER15, ANSWER16, ANSWER17, ANSWER18, ANSWER19, ANSWER20, ANSWER21, ANSWER22, ANSWER23, ANSWER24, RECORDID, NUM, QUESTIONNUM) VALUES ('멜로영화', '빵', '양식', '수족관', '비', '양보다 질', '외모', '정장', '면바지', '스키', '적게 본다', '줍는다', '없다', '세글자', '회전목마', '영화관', '싫다', '얼굴', '화려한색', '낮져밤이', '그냥간다', '국내', '헤어진다', '그렇다', 'webapp', '18', 'a2_b1');
INSERT INTO "SCOTT"."HEARTLINKRECORD" (ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, ANSWER8, ANSWER9, ANSWER10, ANSWER11, ANSWER12, ANSWER13, ANSWER14, ANSWER15, ANSWER16, ANSWER17, ANSWER18, ANSWER19, ANSWER20, ANSWER21, ANSWER22, ANSWER23, ANSWER24, RECORDID, NUM, QUESTIONNUM) VALUES ('양념', '사랑', '짜장 ', '야구', '콜라', '강아지', '단팥빵', '비누냄새', '하얀피부', '물냉면', '많게 본다', '줍는다', '없다', '세글자', '회전목마', '영화관', '싫다', '몸매', '단색', '낮이밤져', '그냥간다', '해외', '도망간다', '아니다', 'webapp', '19', 'a1_b1');
INSERT INTO "SCOTT"."HEARTLINKRECORD" (ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, ANSWER8, ANSWER9, ANSWER10, ANSWER11, ANSWER12, ANSWER13, ANSWER14, ANSWER15, ANSWER16, ANSWER17, ANSWER18, ANSWER19, ANSWER20, ANSWER21, ANSWER22, ANSWER23, ANSWER24, RECORDID, NUM, QUESTIONNUM) VALUES ('후라이드 ', '사랑', '짜장 ', '축구', '콜라', '강아지', '단팥빵', '향수냄새', '하얀피부', '비빔냉면', '많게 본다', '줍는다', '있다', '세글자', '자이로드롭', '영화관', '괜찮다', '몸매', '단색', '낮져밤이', '먹고간다', '국내', '도망간다', '그렇다', 'ltk016', '16', 'a1_b1');
INSERT INTO "SCOTT"."HEARTLINKRECORD" (ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, ANSWER8, ANSWER9, ANSWER10, ANSWER11, ANSWER12, ANSWER13, ANSWER14, ANSWER15, ANSWER16, ANSWER17, ANSWER18, ANSWER19, ANSWER20, ANSWER21, ANSWER22, ANSWER23, ANSWER24, RECORDID, NUM, QUESTIONNUM) VALUES ('후라이드 ', '우정 ', '짜장 ', '야구', '사이다 ', '고양이', '단팥빵', '향수냄새', '까만피부', '비빔냉면', '많게 본다', '줍는다', '없다', '세글자', '자이로드롭', '영화관', '싫다', '몸매', '화려한색', '낮이밤져', '그냥간다', '국내', '헤어진다', '아니다', 'kyh123', '12', 'a1_b1');
INSERT INTO "SCOTT"."HEARTLINKRECORD" (ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, ANSWER8, ANSWER9, ANSWER10, ANSWER11, ANSWER12, ANSWER13, ANSWER14, ANSWER15, ANSWER16, ANSWER17, ANSWER18, ANSWER19, ANSWER20, ANSWER21, ANSWER22, ANSWER23, ANSWER24, RECORDID, NUM, QUESTIONNUM) VALUES ('후라이드 ', '우정 ', '짬뽕', '야구', '사이다 ', '고양이', '크림빵', '비누냄새', '까만피부', '물냉면', '적게 본다', '그냥 지나친다', '없다', '다섯글자', '회전목마', '커피숍', '싫다', '몸매', '화려한색', '낮이밤져', '그냥간다', '해외', '헤어진다', '아니다', 'sunny', '15', 'a1_b1');
INSERT INTO "SCOTT"."HEARTLINKRECORD" (ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, ANSWER8, ANSWER9, ANSWER10, ANSWER11, ANSWER12, ANSWER13, ANSWER14, ANSWER15, ANSWER16, ANSWER17, ANSWER18, ANSWER19, ANSWER20, ANSWER21, ANSWER22, ANSWER23, ANSWER24, RECORDID, NUM, QUESTIONNUM) VALUES ('양념', '우정 ', '짬뽕', '야구', '사이다 ', '고양이', '단팥빵', '향수냄새', '까만피부', '물냉면', '많게 본다', '그냥 지나친다', '없다', '세글자', '자이로드롭', '영화관', '싫다', '몸매', '화려한색', '낮이밤져', '그냥간다', '해외', '도망간다', '그렇다', 'sun', '13', 'a1_b1');
INSERT INTO "SCOTT"."HEARTLINKRECORD" (ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5, ANSWER6, ANSWER7, ANSWER8, ANSWER9, ANSWER10, ANSWER11, ANSWER12, ANSWER13, ANSWER14, ANSWER15, ANSWER16, ANSWER17, ANSWER18, ANSWER19, ANSWER20, ANSWER21, ANSWER22, ANSWER23, ANSWER24, RECORDID, NUM, QUESTIONNUM) VALUES ('양념', '사랑', '짜장 ', '축구', '콜라', '강아지', '크림빵', '향수냄새', '까만피부', '비빔냉면', '많게 본다', '그냥 지나친다', '있다', '다섯글자', '자이로드롭', '영화관', '싫다', '얼굴', '화려한색', '낮이밤져', '그냥간다', '국내', '헤어진다', '그렇다', 'hwan', '14', 'a1_b1');

  
  
  
  
  
