--------------------------------------------------------
--  DDL for Table RQKAKAOID
--------------------------------------------------------

  CREATE TABLE "SCOTT"."RQKAKAOID" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"REQUESTID" VARCHAR2(20 BYTE), 
	"NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RQKAKAOID
--------------------------------------------------------

  ALTER TABLE "SCOTT"."RQKAKAOID" MODIFY ("USERID" NOT NULL ENABLE);







--------------------------------------------------------
--  DDL for Table MATCHINGRECORD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MATCHINGRECORD" 
   (	"ANSWER1" VARCHAR2(100 BYTE), 
	"ANSWER2" VARCHAR2(100 BYTE), 
	"ANSWER3" VARCHAR2(100 BYTE), 
	"ANSWER4" VARCHAR2(100 BYTE), 
	"ANSWER5" VARCHAR2(100 BYTE), 
	"ANSWER6" VARCHAR2(100 BYTE), 
	"ANSWER7" VARCHAR2(100 BYTE), 
	"ANSWER8" VARCHAR2(100 BYTE), 
	"ANSWER9" VARCHAR2(100 BYTE), 
	"ANSWER10" VARCHAR2(100 BYTE), 
	"ANSWER11" VARCHAR2(100 BYTE), 
	"ANSWER12" VARCHAR2(100 BYTE), 
	"ANSWER13" VARCHAR2(100 BYTE), 
	"ANSWER14" VARCHAR2(100 BYTE), 
	"ANSWER15" VARCHAR2(100 BYTE), 
	"ANSWER16" VARCHAR2(100 BYTE), 
	"ANSWER17" VARCHAR2(100 BYTE), 
	"ANSWER18" VARCHAR2(100 BYTE), 
	"ANSWER19" VARCHAR2(100 BYTE), 
	"ANSWER20" VARCHAR2(100 BYTE), 
	"ANSWER21" VARCHAR2(100 BYTE), 
	"ANSWER22" VARCHAR2(100 BYTE), 
	"ANSWER23" VARCHAR2(100 BYTE), 
	"ANSWER24" VARCHAR2(100 BYTE), 
	"RECORDID" VARCHAR2(100 BYTE), 
	"QUESTIONNUM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MATCHINGRECORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."MATCHINGRECORD_PK" ON "SCOTT"."MATCHINGRECORD" ("RECORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MATCHINGRECORD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MATCHINGRECORD" ADD CONSTRAINT "MATCHINGRECORD_PK" PRIMARY KEY ("RECORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."MATCHINGRECORD" MODIFY ("RECORDID" NOT NULL ENABLE);














--------------------------------------------------------
--  DDL for Table HEARTLINKRECORD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."HEARTLINKRECORD" 
   (	"ANSWER1" VARCHAR2(100 BYTE), 
	"ANSWER2" VARCHAR2(100 BYTE), 
	"ANSWER3" VARCHAR2(100 BYTE), 
	"ANSWER4" VARCHAR2(100 BYTE), 
	"ANSWER5" VARCHAR2(100 BYTE), 
	"ANSWER6" VARCHAR2(100 BYTE), 
	"ANSWER7" VARCHAR2(100 BYTE), 
	"ANSWER8" VARCHAR2(100 BYTE), 
	"ANSWER9" VARCHAR2(100 BYTE), 
	"ANSWER10" VARCHAR2(100 BYTE), 
	"ANSWER11" VARCHAR2(100 BYTE), 
	"ANSWER12" VARCHAR2(100 BYTE), 
	"ANSWER13" VARCHAR2(100 BYTE), 
	"ANSWER14" VARCHAR2(100 BYTE), 
	"ANSWER15" VARCHAR2(100 BYTE), 
	"ANSWER16" VARCHAR2(100 BYTE), 
	"ANSWER17" VARCHAR2(100 BYTE), 
	"ANSWER18" VARCHAR2(100 BYTE), 
	"ANSWER19" VARCHAR2(100 BYTE), 
	"ANSWER20" VARCHAR2(100 BYTE), 
	"ANSWER21" VARCHAR2(100 BYTE), 
	"ANSWER22" VARCHAR2(100 BYTE), 
	"ANSWER23" VARCHAR2(100 BYTE), 
	"ANSWER24" VARCHAR2(100 BYTE), 
	"RECORDID" VARCHAR2(100 BYTE), 
	"NUM" NUMBER(*,0), 
	"QUESTIONNUM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HEARTLINKRECORD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."HEARTLINKRECORD" MODIFY ("RECORDID" NOT NULL ENABLE);




















--------------------------------------------------------
--  DDL for Table NOTE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."NOTE" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"MESSAGE" VARCHAR2(100 BYTE), 
	"NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;





















--------------------------------------------------------
--  DDL for Table PICTURE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PICTURE" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"PICBYTES" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PICBYTES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;






















--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PROFILE" 
   (	"MESSAGE" VARCHAR2(300 BYTE), 
	"USERID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;























--------------------------------------------------------
--  DDL for Table QnA테이블!!!!!!!!!!!!
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ARTICLE" 
   (	"ID" NUMBER, 
	"WRITERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index ARTICLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ARTICLE_PK" ON "SCOTT"."ARTICLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ARTICLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ARTICLE" MODIFY ("WRITERNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ARTICLE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ARTICLE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ARTICLE" ADD CONSTRAINT "ARTICLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;




























--------------------------------------------------------
--  DDL for Table 멤버 테이블!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MEMBER" 
   (	"RGID" VARCHAR2(20 BYTE), 
	"RGPASSWORD" VARCHAR2(100 BYTE), 
	"RGBIRTH" NUMBER, 
	"RGSEX" VARCHAR2(20 BYTE), 
	"RGAREA" VARCHAR2(20 BYTE), 
	"KAKAOID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGISTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."REGISTER_PK" ON "SCOTT"."MEMBER" ("RGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGBIRTH" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("KAKAOID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGSEX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGAREA" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" ADD CONSTRAINT "REGISTER_PK" PRIMARY KEY ("RGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
























--------------------------------------------------------
--  DDL for Table QUESTION
--------------------------------------------------------

  CREATE TABLE "SCOTT"."QUESTION" 
   (	"SEL_1" VARCHAR2(100 BYTE), 
	"SEL_2" VARCHAR2(100 BYTE), 
	"SEL_3" VARCHAR2(100 BYTE), 
	"NUM" NUMBER, 
	"BIND" VARCHAR2(20 BYTE), 
	"VALUE" VARCHAR2(20 BYTE), 
	"FORNAME1" VARCHAR2(20 BYTE), 
	"FORNAME2" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
  
  
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 1', '양념', '후라이드 ', '1', 's1', 'name1', 'name2', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 2', '사랑', '우정 ', '2', 's2', 'name3', 'name4', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 3', '짜장 ', '짬뽕', '3', 's3', 'name5', 'name6', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 4', '축구', '야구', '4', 's4', 'name7', 'name8', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 5', '콜라', '사이다 ', '5', 's5', 'name9', 'name10', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 6', '강아지', '고양이', '6', 's6', 'name11', 'name12', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 7', '단팥빵', '크림빵', '7', 's7', 'name13', 'name14', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 8', '향수냄새', '비누냄새', '8', 's8', 'name15', 'name16', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 9', '하얀피부', '까만피부', '9', 's9', 'name17', 'name18', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 10', '비빔냉면', '물냉면', '10', 's10', 'name19', 'name20', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('주위에서 바라보는 자신의 연령은?', '많게 본다', '적게 본다', '11', 's11', 'name21', 'name22', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('길을 걷는중에 100원짜리 동전이 눈앞에 떨어져 있다 ', '줍는다', '그냥 지나친다', '12', 's12', 'name23', 'name24', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('귀신이 있다고 생각하나?', '있다', '없다', '13', 's13', 'name25', 'name26', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('몇글자 인가?', '세글자', '다섯글자', '14', 's14', 'name27', 'name28', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('둘중에 더 좋아하는 놀이기구는?', '자이로드롭', '회전목마', '15', 's15', 'name29', 'name30', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('첫 데이트 장소로 적합한 곳은?', '영화관', '커피숍', '16', 's16', 'name31', 'name32', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인이 갑자기 살이 많이 쪘다', '괜찮다', '싫다', '17', 's17', 'name33', 'name34', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('이성을 처음 볼때 먼저 보는 곳', '얼굴', '몸매', '18', 's18', 'name35', 'name36', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('이성이 입었으면 하는 속옷 색은?', '단색', '화려한색', '19', 's19', 'name37', 'name38', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('자신의 성적 성향은?', '낮져밤이', '낮이밤져', '20', 's20', 'name39', 'name40', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인이 라면 먹고 가라고 속삭인다', '먹고간다', '그냥간다', '21', 's21', 'name41', 'name42', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('신혼여행 장소는?', '국내', '해외', '22', 's22', 'name43', 'name44', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('부모님이 결혼을 반대한다면?', '도망간다', '헤어진다', '23', 's23', 'name45', 'name46', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('밥은 여자가 차려야 한다', '그렇다', '아니다', '24', 's24', 'name47', 'name48', 'a1_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 1', '양념', '후라이드 ', '1', 's1', 'name1', 'name2', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 2', '사랑', '우정 ', '2', 's2', 'name3', 'name4', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 3', '짜장 ', '짬뽕', '3', 's3', 'name5', 'name6', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 4', '축구', '야구', '4', 's4', 'name7', 'name8', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 5', '콜라', '사이다 ', '5', 's5', 'name9', 'name10', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 6', '강아지', '고양이', '6', 's6', 'name11', 'name12', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 7', '단팥빵', '크림빵', '7', 's7', 'name13', 'name14', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 8', '향수냄새', '비누냄새', '8', 's8', 'name15', 'name16', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 9', '하얀피부', '까만피부', '9', 's9', 'name17', 'name18', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 10', '비빔냉면', '물냉면', '10', 's10', 'name19', 'name20', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('연예인이 사귀자고 한다', '사귄다', '안사귄다', '11', 's11', 'name21', 'name22', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('선호하는 핸드폰은?', '아이폰', '갤럭시', '12', 's12', 'name23', 'name24', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('길가다 넘어졌다', '바로 일어난다', '계속 누워있는다', '13', 's13', 'name25', 'name26', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('보이스피싱 전화가 걸려왔다', '바로 끊는다', '장난치다 끊는다', '14', 's14', 'name27', 'name28', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('할일이 생겼다면', '바로 시작한다', '미룬다', '15', 's15', 'name29', 'name30', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인과 다툼을 하였을때', '그 자리에서 끝을 본다', '시간을 갖고 생각정리를 먼저 한다', '16', 's16', 'name31', 'name32', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인에게 먼저 연락을 자주 하는가?', '그렇다', '아니다', '17', 's17', 'name33', 'name34', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('단칸방부터 결혼생활을 시작할 수 있나?', '있다', '없다', '18', 's18', 'name35', 'name36', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('혼전순결인가?', '그렇다', '아니다', '19', 's19', 'name37', 'name38', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('결혼 후 어디서 살것인가?', '분가한다', '양가부모님과 산다', '20', 's20', 'name39', 'name40', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인이 자신과 연예인을 비교한다면?', '똑같이 대응한다', '쿨하게 인정한다', '21', 's21', 'name41', 'name42', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('혼수는 해야 한다고 생각하나?', '그렇다', '아니다', '22', 's22', 'name43', 'name44', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('결혼전 동거가 가능한가?', '가능', '불가능', '23', 's23', 'name45', 'name46', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('질투가 많은 편인가?', '그렇다', '아니다', '24', 's24', 'name47', 'name48', 'a1_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 1', '양념', '후라이드 ', '1', 's1', 'name1', 'name2', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 2', '사랑', '우정 ', '2', 's2', 'name3', 'name4', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 3', '짜장 ', '짬뽕', '3', 's3', 'name5', 'name6', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 4', '축구', '야구', '4', 's4', 'name7', 'name8', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 5', '콜라', '사이다 ', '5', 's5', 'name9', 'name10', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 6', '강아지', '고양이', '6', 's6', 'name11', 'name12', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 7', '단팥빵', '크림빵', '7', 's7', 'name13', 'name14', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 8', '향수냄새', '비누냄새', '8', 's8', 'name15', 'name16', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 9', '하얀피부', '까만피부', '9', 's9', 'name17', 'name18', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 10', '비빔냉면', '물냉면', '10', 's10', 'name19', 'name20', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('거짓말 한 것이 들통날 것 같다면?', '자백한다', '끝까지 간다', '11', 's11', 'name21', 'name22', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('배고픈데 잠이 온다면?', '먹고잔다', '그냥잔다', '12', 's12', 'name23', 'name24', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('길을 걷다가 지갑을 주웠다', '주인을 찾아준다', '자신이 가진다', '13', 's13', 'name25', 'name26', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('이상형이 지나간다', '데쉬한다 ', '그냥간다', '14', 's14', 'name27', 'name28', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('영화를 볼 사람이 없다면?', '혼자 보러 간다', '보러가지 않는다', '15', 's15', 'name29', 'name30', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('데이트 비용이 없다면?', '만난다', '만나지 않는다', '16', 's16', 'name31', 'name32', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('이성친구가 바람을 피우다 걸렸다', '맞바람을 핀다', '헤어진다', '17', 's17', 'name33', 'name34', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('결혼 전 동거가 가능한가?', '가능', '불가능', '18', 's18', 'name35', 'name36', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인과 종교가 다르다면?', '맞춰가야한다', '달라도 된다', '19', 's19', 'name37', 'name38', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('원하는 이성의 성향은?', '비슷한 성향', '반대의 성향', '20', 's20', 'name39', 'name40', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('좋아한다면 나이는 상관없다?', '상관있다', '상관없다', '21', 's21', 'name41', 'name42', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('결혼 혼인신고 할것인가?', '한다', '안한다', '22', 's22', 'name43', 'name44', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인이 공공장소에서 스킨쉽을 시도한다면?', '한다', '거부한다', '23', 's23', 'name45', 'name46', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('사랑한다면 잠자리까지 가는 기간은 기간은 중요하지 않다', '중요하다', '중요하지 않다', '24', 's24', 'name47', 'name48', 'a1_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 1', '멜로영화', '공포영화', '1', 's1', 'name1', 'name2', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 2', '떡', '빵', '2', 's2', 'name3', 'name4', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 3', '양식', '한식', '3', 's3', 'name5', 'name6', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 4', '동물원', '수족관', '4', 's4', 'name7', 'name8', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 5', '눈', '비', '5', 's5', 'name9', 'name10', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 6', '양보다 질', '질보다 양', '6', 's6', 'name11', 'name12', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 7', '성격', '외모', '7', 's7', 'name13', 'name14', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 8', '정장', '캐주얼', '8', 's8', 'name15', 'name16', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 9', '청바지', '면바지', '9', 's9', 'name17', 'name18', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 10', '스키', '보드', '10', 's10', 'name19', 'name20', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('주위에서 바라보는 자신의 연령은?', '많게 본다', '적게 본다', '11', 's11', 'name21', 'name22', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('길을 걷는중에 100원짜리 동전이 눈앞에 떨어져 있다 ', '줍는다', '그냥 지나친다', '12', 's12', 'name23', 'name24', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('귀신이 있다고 생각하나?', '있다', '없다', '13', 's13', 'name25', 'name26', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('몇글자 인가?', '세글자', '다섯글자', '14', 's14', 'name27', 'name28', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('둘중에 더 좋아하는 놀이기구는?', '자이로드롭', '회전목마', '15', 's15', 'name29', 'name30', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('첫 데이트 장소로 적합한 곳은?', '영화관', '커피숍', '16', 's16', 'name31', 'name32', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인이 갑자기 살이 많이 쪘다', '괜찮다', '싫다', '17', 's17', 'name33', 'name34', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('이성을 처음 볼때 먼저 보는 곳', '얼굴', '몸매', '18', 's18', 'name35', 'name36', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('자신의 성적 성향은?', '낮져밤이', '낮이밤져', '20', 's20', 'name39', 'name40', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인이 라면 먹고 가라고 속삭인다', '먹고간다', '그냥간다', '21', 's21', 'name41', 'name42', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('신혼여행 장소는?', '국내', '해외', '22', 's22', 'name43', 'name44', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('부모님이 결혼을 반대한다면?', '도망간다', '헤어진다', '23', 's23', 'name45', 'name46', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('밥은 여자가 차려야 한다', '그렇다', '아니다', '24', 's24', 'name47', 'name48', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 1', '멜로영화', '공포영화', '1', 's1', 'name1', 'name2', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('이성이 입었으면 하는 속옷 색은?', '단색', '화려한색', '19', 's19', 'name37', 'name38', 'a2_b1');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 2', '떡', '빵', '2', 's2', 'name3', 'name4', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 3', '양식', '한식', '3', 's3', 'name5', 'name6', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 4', '동물원', '수족관', '4', 's4', 'name7', 'name8', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 5', '눈', '비', '5', 's5', 'name9', 'name10', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 6', '양보다 질', '질보다 양', '6', 's6', 'name11', 'name12', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 7', '성격', '외모', '7', 's7', 'name13', 'name14', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 8', '정장', '캐주얼', '8', 's8', 'name15', 'name16', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 9', '청바지', '면바지', '9', 's9', 'name17', 'name18', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 10', '스키', '보드', '10', 's10', 'name19', 'name20', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('연예인이 사귀자고 한다', '사귄다', '안사귄다', '11', 's11', 'name21', 'name22', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('선호하는 핸드폰은?', '아이폰', '갤럭시', '12', 's12', 'name23', 'name24', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('길가다 넘어졌다', '바로 일어난다', '계속 누워있는다', '13', 's13', 'name25', 'name26', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('보이스피싱 전화가 걸려왔다', '바로 끊는다', '장난치다 끊는다', '14', 's14', 'name27', 'name28', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('할일이 생겼다면', '바로 시작한다', '미룬다', '15', 's15', 'name29', 'name30', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인과 다툼을 하였을때', '그 자리에서 끝을 본다', '시간을 갖고 생각정리를 먼저 한다', '16', 's16', 'name31', 'name32', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인에게 먼저 연락을 자주 하는가?', '그렇다', '아니다', '17', 's17', 'name33', 'name34', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('단칸방부터 결혼생활을 시작할 수 있나?', '있다', '없다', '18', 's18', 'name35', 'name36', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('혼전순결인가?', '그렇다', '아니다', '19', 's19', 'name37', 'name38', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('결혼 후 어디서 살것인가?', '분가한다', '양가부모님과 산다', '20', 's20', 'name39', 'name40', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인이 자신과 연예인을 비교한다면?', '똑같이 대응한다', '쿨하게 인정한다', '21', 's21', 'name41', 'name42', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('혼수는 해야 한다고 생각하나?', '그렇다', '아니다', '22', 's22', 'name43', 'name44', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('결혼전 동거가 가능한가?', '가능', '불가능', '23', 's23', 'name45', 'name46', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('질투가 많은 편인가?', '그렇다', '아니다', '24', 's24', 'name47', 'name48', 'a2_b2');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 1', '멜로영화', '공포영화', '1', 's1', 'name1', 'name2', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 2', '떡', '빵', '2', 's2', 'name3', 'name4', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 3', '양식', '한식', '3', 's3', 'name5', 'name6', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 4', '동물원', '수족관', '4', 's4', 'name7', 'name8', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 5', '눈', '비', '5', 's5', 'name9', 'name10', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 6', '양보다 질', '질보다 양', '6', 's6', 'name11', 'name12', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 7', '성격', '외모', '7', 's7', 'name13', 'name14', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 8', '정장', '캐주얼', '8', 's8', 'name15', 'name16', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 9', '청바지', '면바지', '9', 's9', 'name17', 'name18', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('양자택일 10', '스키', '보드', '10', 's10', 'name19', 'name20', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('거짓말 한 것이 들통날 것 같다면?', '자백한다', '끝까지 간다', '11', 's11', 'name21', 'name22', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('배고픈데 잠이 온다면?', '먹고잔다', '그냥잔다', '12', 's12', 'name23', 'name24', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('길을 걷다가 지갑을 주웠다', '주인을 찾아준다', '자신이 가진다', '13', 's13', 'name25', 'name26', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('이상형이 지나간다', '데쉬한다 ', '그냥간다', '14', 's14', 'name27', 'name28', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('영화를 볼 사람이 없다면?', '혼자 보러 간다', '보러가지 않는다', '15', 's15', 'name29', 'name30', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('데이트 비용이 없다면?', '만난다', '만나지 않는다', '16', 's16', 'name31', 'name32', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('이성친구가 바람을 피우다 걸렸다', '맞바람을 핀다', '헤어진다', '17', 's17', 'name33', 'name34', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('결혼 전 동거가 가능한가?', '가능', '불가능', '18', 's18', 'name35', 'name36', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인과 종교가 다르다면?', '맞춰가야한다', '달라도 된다', '19', 's19', 'name37', 'name38', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('원하는 이성의 성향은?', '비슷한 성향', '반대의 성향', '20', 's20', 'name39', 'name40', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('좋아한다면 나이는 상관없다?', '상관있다', '상관없다', '21', 's21', 'name41', 'name42', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('결혼 혼인신고 할것인가?', '한다', '안한다', '22', 's22', 'name43', 'name44', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('애인이 공공장소에서 스킨쉽을 시도한다면?', '한다', '거부한다', '23', 's23', 'name45', 'name46', 'a2_b3');
INSERT INTO "SCOTT"."QUESTION" (SEL_1, SEL_2, SEL_3, NUM, BIND, FORNAME1, FORNAME2, TYPE) VALUES ('사랑한다면 잠자리까지 가는 기간은 기간은 중요하지 않다', '중요하다', '중요하지 않다', '24', 's24', 'name47', 'name48', 'a2_b3');

  
  
  
  
  
  

  
