--------------------------------------------------------
--  파일이 생성됨 - 수요일-5월-13-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MEMBER" 
   (	"RGID" VARCHAR2(20 BYTE), 
	"RGPASSWORD" VARCHAR2(20 BYTE), 
	"RGBIRTH" NUMBER, 
	"RGSEX" VARCHAR2(20 BYTE), 
	"RGAREA" VARCHAR2(20 BYTE), 
	"KAKAOID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGISTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."REGISTER_PK" ON "SCOTT"."MEMBER" ("RGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MEMBER" ADD CONSTRAINT "REGISTER_PK" PRIMARY KEY ("RGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGAREA" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGSEX" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("KAKAOID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGBIRTH" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("RGID" NOT NULL ENABLE);
  
  
  
  
  
  INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('webapp', '1234', '1999', 'mail', '서울', 'kakaka');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('sjsm111', '1234', '232', 'mail', '인천', '2334');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('sjsm222', '1234', '214', 'mail', '강원', 'sdf');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('sjsm333', '1234', '234', 'mail', '서울', 'sdf');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('b890223', '12345', '890223', 'femail', '서울', 'aa');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('shkjl2006', '1234', '19910515', 'mail', '서울', 'ssss');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('sunny', '1234', '890113', 'femail', '인천', 'sunny');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('qwer1234', '1234', '1987', 'mail', '서울', 'asxh');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('aaaa', '1234', '19860312', 'mail', '서울', 'black');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('ltk016', '1q2w3e', '881219', 'mail', '서울', 'ltk016');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('ltk0166', '1q2w3e', '123456', 'femail', '서울', 'ltk016');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('masayuki86', '1234', '861008', 'mail', '서울', 'TheMray');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('kmh880528', '987qshg', '880528', 'femail', '서울', 'kmh880528');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('jo', '26578', '870122', 'mail', '서울', 'qkftntu1@naver.com');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('id', 'pass', '1223', 'mail', '서울', 'sdwsd');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('sdfsdf', '123', '234', 'mail', '강원', 'sdf');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('kyh123', '1234', '1987', 'mail', '서울', 'aaaaa');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('hwan', '1234', '861226', 'mail', '서울', 'ash37373');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('sun', '1234', '890113', 'femail', '인천', 'sun');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('heartlink', '1234', '24', '24', '남', 'kakakaka');
INSERT INTO "SCOTT"."MEMBER" (RGID, RGPASSWORD, RGBIRTH, RGSEX, RGAREA, KAKAOID) VALUES ('chae1989', '1989', '890224', 'femail', '인천', 'chae1989');

