--------------------------------------------------------
--  颇老捞 积己凳 - 老夸老-5岿-17-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PROFILE" 
   (	"MESSAGE" VARCHAR2(300 BYTE), 
	"USERID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('rtyrt', 'webapp');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('sdfsd', 'kakaka');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('fddfg', '2334');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('dfg', 'sdf');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('dfg', 'sdf');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('dfgdfgfd', 'aa');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('dggdf', 'ssss');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('dgfd', 'sunny');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('ghj', 'asxh');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('jhkjkh', 'black');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('hjkkhj', 'ltk016');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('hjkjh', 'TheMray');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('rty', 'kmh880528');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('vbn', 'qkftntu1@naver.com');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('dgd', 'sdwsd');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('erte', 'sdf');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('fgh', 'aaaaa');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('sdf', 'ash37373');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('sdf', 'sun');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('ert', 'kakakaka');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('sd', 'chae1989');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('fgh', 'sdsd');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('sdds', 'shkjl2006');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('sdsdsdds', 'masayuki86');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('sdsd', 'kyh123');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('sdsdsd', 'b890223');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('sdfsdfsdf', 'jo');
INSERT INTO "SCOTT"."PROFILE" (MESSAGE, USERID) VALUES ('fsdgdgdgf', 'aaaa');
